# This docker-compose file is to run tests on Docker.
version: "3.7"

services:
  test:
    build:
      context: .
      dockerfile: ./.testcontainer/Dockerfile
      args:
        - NAME_IMAGE=php:7.4.3-cli-alpine
    environment:
      - COVERALLS_REPO_TOKEN
    # Mount file/dir that might be changed after docker build
    volumes:
      - ./composer.json:/app/composer.json
      - ./.git/:/app/.git
      - ./bin:/app/bin
      - ./samples:/app/samples
      - ./src:/app/src
      - ./tests:/app/tests
      - ./report:/app/report
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    environment:
      - COVERALLS_REPO_TOKEN
    volumes:
      - .:/app
